services:
  bookmarks-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - bookmarks-app-networks
    restart: on-failure

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookmarks_db
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - bookmarks-app-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  bookmarks-app-networks:
    driver: bridge

volumes:
  mysql-db-data: